### ISSUE TITLE
Not visible on minimap

### ISSUE THREAD

**Issue by SrPeterr** [TayMcKenzieNZ/CayoTwoIslands#1]
Hi!
For some reason I see the map like this:
![image](https://user-images.githubusercontent.com/21348463/156007721-7079eccb-dc3a-4231-b7c4-41b85c251422.png)

I am using map-atlas but I did use this too https://forum.cfx.re/t/exclusivity-cayo-perico-island-color-minimap/2003927
But same, the LS map works but CayoPerico nope :(

**Comment by TayMcKenzieNZ** [comment]
# BUGS 🐛

- Los Santos and Cayo Perico will **ONLY** both show up on the minimap / pause map, if the player is **on** or **near** Cayo Perico. This is due to how GTA 5 handles it. 

- Cayo Perico's minimap is handled the same way as interiors, therefore **if** code is added to force both minimaps to appear, when a player enters a different location such as Vanilla Unicorn for example, the minimap will not change or show that they are inside an interior.

I have added map blips if you wish to fly a plane or drive a boat there. 

Stop spamming about it as I have already made this apparent. For those who have actually read this part, feel free to quote it and reply to those with 2 brains cells. Thanks 😛

 - Conflicts with Cayo Perico Shops 2, use the first release instead

- *some people* claim to have fixed the issue with this resource and Rockstar Editor, however it is behind a paywall and FiveM's escrow nonsense. The FiveM team have pushed an update as of February 8th 2022 to hopefully [fix this](https://forum.cfx.re/t/cfx-re-client-update-fivem-redm-for-february-8th-2022/4813410)

**Comment by TayMcKenzieNZ** [comment]
Minimap now fixed
